"use client";
import { Provider } from "react-redux";
// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

import { ny } from "@/lib/utils";

import { Inter as FontSans } from "next/font/google";
import { store } from "./store";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ny(`min-h-screen bg-background font-sans antialiased`, fontSans.variable)}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
